### ISSUE TITLE
How to encode existing image?

### ISSUE THREAD

**Issue by tambetm** [orpatashnik/StyleCLIP#10]
The README suggests using [e2e](https://github.com/omertov/encoder4editing) for encoding existing face image, but this repo seems to be empty. I tried using [stylegan-encoder](https://github.com/Puzer/stylegan-encoder) instead, but it is based on Tensorflow and I got stuck with downloading the model with "Google Drive quota exceeded" error. Any suggestions for what to use for StyleGAN encoding?

**Comment by orpatashnik** [comment]
Hi @tambetm ,
Thanks for your interest!
Until the code of e4e will be released, I recommend using pSp. You can refer to [this issue](https://github.com/orpatashnik/StyleCLIP/issues/1) for additional details. Let me know if it works for you 😊

**Comment by tambetm** [comment]
Thanks! Closing this as duplicate to #1.

**Comment by woctezuma** [comment]
FYI e4e has been released! [![Open In Colab][colab-badge]][colab-encoder4editing]

[colab-badge]: <https://colab.research.google.com/assets/colab-badge.svg>
[colab-encoder4editing]: <http://colab.research.google.com/github/omertov/encoder4editing/blob/main/notebooks/inference_playground.ipynb>
