### ISSUE TITLE
Google Colab removed support for TensorFlow 1.

### ISSUE THREAD

**Issue by ZziTaiLeo** [orpatashnik/StyleCLIP#102]
I get errors in the colab. "Your notebook should be updated to use Tensorflow 2."
I found that Google Colab removed support for TensorFlow 1.

**Comment by betterze** [comment]
We add support for global direction with torch implementation in [here](https://colab.research.google.com/github/orpatashnik/StyleCLIP/blob/main/notebooks/StyleCLIP_global_torch.ipynb)
