### ISSUE TITLE
Latent Mapper never trains

### ISSUE THREAD

**Issue by RahulBhalley** [orpatashnik/StyleCLIP#107]
Hi, thanks for StyleCLIP work.

But when I train Latent Mapper using instructions under [Editing via Latent Mapper](https://github.com/orpatashnik/StyleCLIP#editing-via-latent-mapper) section my latent mapper just never trains.

I get a `best_model.pt` of 145.34 MB. whereas latent mapper (including all 3 spatial control levels) is just 12.6 MB. So I put extract the mapper parameters and load them in a new `latent_mappers.LevelsMapper` instance. But then I do inference while traversing in latent space in the direction of what new LevelsMapper well trained. Something like this: `new_latent = latent_code_init + mapper(latent_code_init) * I` but there are not manipulations happening in image.

Here are samples (initial image and manipulated image).

### 1) For description "bob-cut hairstyle"
![0_0 0](https://user-images.githubusercontent.com/9640948/211701584-286c4ebf-ea08-4a7c-a880-856b06b01a35.jpg)
![19_0 095](https://user-images.githubusercontent.com/9640948/211701605-56cb7a0d-ce11-4f27-bf13-b15b174895b9.jpg)

### 2) For description "smiling face"
![0_0 0](https://user-images.githubusercontent.com/9640948/211701769-0686ad08-21e5-4582-9774-2044dc93ec7a.jpg)
![49_0 098](https://user-images.githubusercontent.com/9640948/211701777-55daeecd-6525-4e8c-9493-6dd85b02dd14.jpg)

**Comment by RahulBhalley** [comment]
Just found out that it does work but only if I load decoder parameters too. But shouldn't that be locked during training? I mean, aren't we supposed to change _only_ latent mapper to manipulate different aspect of an image?

**Comment by stas-polukeev** [comment]
hi! could you provide the commands you used for training, please? I'm trying the same, but the generator doesn't seem to work correctly
