### ISSUE TITLE
CUDA out of memory when using own latent

### ISSUE THREAD

**Issue by GaetanDeWaele** [orpatashnik/StyleCLIP#11]
Hi, great repo, love the idea.

I have an issue with CUDA memory in the Google Colab playground notebook:
`CUDA out of memory. Tried to allocate 1.12 GiB (GPU 0; 14.76 GiB total capacity; 13.61 GiB already allocated; 75.75 MiB free; 13.76 GiB reserved in total by PyTorch)`

It happens at the start of the optimization process.
I have used the recommended e4e to invert my own image.
If relevant: the size of the latent is `torch.Size([18, 512])`.

Is there any easy way to reduce the memory footprint of the notebook?

Thanks in advance.

**Comment by orpatashnik** [comment]
Hi @GaetanDeWaele ,
Glad that you like the repo!
When the StyleGAN generator receives an input with the shape that you mentioned, it relates to it as 18 different vectors, and tries to generate 18 images. I believe that if you will do `.unsqueeze(0)` before saving the latent code, the problem should be solved.
Please let me know if it is indeed the issue.

**Comment by GaetanDeWaele** [comment]
Of course, makes perfect sense.
Solved & closed!
