### ISSUE TITLE
Some question about global_torch

### ISSUE THREAD

**Issue by junyizeng** [orpatashnik/StyleCLIP#112]
Thank you very much for your open source. In the reproduction of optimization and mapper, I saw amazing results, but I will reproduce your global_ Torch encountered some difficulties. First of all, you provided a website in StyleCLIP to download the pre training model, but when I used torch. load to load it, the following error occurred. How can I resolve it? In addition, can you share the test code for an experiment that does not appear to have the FFHQ dataset given in your paper?
![image](https://user-images.githubusercontent.com/80525097/227787261-47bccd00-ae40-4c7c-86e5-2df50731b583.png)
![image](https://user-images.githubusercontent.com/80525097/227787308-6714259f-4bf4-4ca6-84e8-3352289a51ff.png)

**Comment by betterze** [comment]
Dear Junyizeng，

Thank you for your interest in our work.

Did you download the checkpoint from https://drive.google.com/file/d/1FlAb1rYa0r_--Zj_ML8e6shmaF28hQb5/view ? You need to go there page and click download. Directly wget will not work. It seems the checkpoint you download is corrupt. 

Thank you for your help.

Best Wishes,

Zongze

**Comment by junyizeng** [comment]
Hello, I have downloaded the corresponding pre-trained model according to the URL you provided, but the previous error still occurs.

**Comment by betterze** [comment]
I just try the codes in [codelab](https://colab.research.google.com/github/orpatashnik/StyleCLIP/blob/main/notebooks/StyleCLIP_global_torch.ipynb), and it works well. 

Please just run the 'Setup (may take a few minutes)' section. Then download the checkpoint from google drive, upload it to codelab (this will take a few mins, pls make sure the uploading is completed), change the model path in [here](https://github.com/orpatashnik/StyleCLIP/blob/main/global_torch/StyleCLIP.py#L187). 

then add a cell after 'setup', and run  

```
cd /content/StyleCLIP/global_torch/
!python StyleCLIP.py
```

This works well for me. If you meet other problems, please show me the errors. Thx

**Comment by junyizeng** [comment]
Thank you very much for your reply, the problem has been solved.
