### ISSUE TITLE
[Question] How to generate images without optimization

### ISSUE THREAD

**Issue by tommy19970714** [orpatashnik/StyleCLIP#13]
Awesome paper! It is an excellent result.
I watched the [youtube video](https://www.youtube.com/watch?v=5icI0NgALnQ) that you uploaded yesterday.
In the demo, it generates images in real-time without optimization.
When I experimented with your [colab](http://colab.research.google.com/github/orpatashnik/StyleCLIP/blob/main/playground.ipynb), I had to optimize it for each text.
How do you generate images like the youtube demo?
If possible, it would be great if you could publish the code of the youtube demo.

**Comment by orpatashnik** [comment]
Hi @tommy19970714 ,
Thanks for your interest in our paper!
We are working on organizing all the code right now. Hopefully it will be released in the next few days!

**Comment by tommy19970714** [comment]
I checked your [notebook](https://colab.research.google.com/github/orpatashnik/StyleCLIP/blob/main/StyleCLIP_global.ipynb) that you uploaded.
Thank you very much for your sharing!
