### ISSUE TITLE
The choice of parameters

### ISSUE THREAD

**Issue by weihaox** [orpatashnik/StyleCLIP#2]
Thank you for sharing. 

I played on the [colab](http://colab.research.google.com/github/orpatashnik/StyleCLIP/blob/main/playground.ipynb) and obtained unpleasing results at most time. It is hard to decide what vaule to use if different edits require different parameters of the CLIP loss. 

Then I tried to use the pretrained CLIP model in my own work [TediGAN](https://github.com/weihaox/TediGAN) and the obtained results are not sensitive to the weights. Adding additional [perceptual loss and image reconstruction loss](https://github.com/weihaox/TediGAN/blob/main/idinvert_pytorch/utils/inverter.py#L197-L222) may help stabilize the optimization process.

![clip_results](https://user-images.githubusercontent.com/54136324/108024469-97728180-705f-11eb-8ef9-3d50c7a7a62d.jpg)

**Comment by orpatashnik** [comment]
Hi @weihaox ,

Thanks for your interest!
I agree that the parameters tuning may be a bit challenging at the moment, this is only an initial version of my project and I hope that I will be able to improve it.
I was not aware of TediGAN, thanks for sharing, looks interesting.

Anyway, according to the results, which text prompt did you use? From the way that the images look, I believe that the issue may be the quality of the inversion. 
You may want to look at this [paper](https://arxiv.org/abs/2102.02766), where we discuss the intimate relation between and editing in StyleGAN's latent space. The encoder's (from the paper) code will hopefully be publicly available within the few next days, and I am pretty confident that it will improve your results.

**Comment by weihaox** [comment]
Thank you for your reply.  I am looking forward to the new version.
