### ISSUE TITLE
Using a user-specified image for the Global Directions Colab Notebook

### ISSUE THREAD

**Issue by minimaxir** [orpatashnik/StyleCLIP#21]
The [Colab notebook](http://colab.research.google.com/github/omertov/encoder4editing/blob/main/notebooks/inference_playground.ipynb) for [e2e](https://github.com/omertov/encoder4editing) creates a `(1, 18, 512)` latent vector which works with the Global Optimization network. However the Global Directions Notebook wants a 26-element list with 15 512-vectors, 3 256-vectors, 3 128-vectors, 3 64-vectors, and 2 32-vectors.

How do you get a compatible vector from e2e for custom images to global directions?

**Comment by betterze** [comment]
Dear Max,

Thank you for your interest in our wok. We just add support to custom images. You may follow the example [codes](https://github.com/orpatashnik/StyleCLIP#usage-1) to use custom model.

Specifically, if you are using the GUI, please use e4e encoder to generate latents.pt, and place it in './data/dataset_name/' folder, and run 

```
python GetGUIData.py --dataset_name $dataset_name --real
```

Then open the GUI, so you could manipulate your images directly. 

If you are using colab, please upload the latents.pt, and do the following step right after 'Select dataset' section,

```
latents=torch.load('latents.pt')
w_plus=latents.cpu().detach().numpy()
M.dlatents=M.W2S(w_plus)
```

Best Wishes,

Alex

**Comment by minimaxir** [comment]
Thanks Alex! That Colab code works! (I'll note the `img_index` must also be `0`)

The **choose image index** collapsed cell now looks like:

```py
latents=torch.load('latents.pt') # located in /StyleCLIP/global
w_plus=latents.cpu().detach().numpy()
dlatents_loaded=M.W2S(w_plus)

img_index = 0
img_indexs=[img_index]

dlatent_tmp=[tmp[img_indexs] for tmp in dlatents_loaded]
M.num_images=len(img_indexs)

M.alpha=[0]
M.manipulate_layers=[0]
codes,out=M.EditOneC(0, dlatent_tmp) 
original=Image.fromarray(out[0,0]).resize((512,512))
M.manipulate_layers=None
original
```

Thanks again!

**Comment by TomatoBoy90** [comment]
when I use M.EditOneC(0, dlatent_tmp),it comes:
No default TensorFlow session found. Please call dnnlib.tflib.init_tf()

**Comment by betterze** [comment]
@TomatoBoy90 How did you load the model? Do you run the LoadModel function in manipulate.py? I add tflib.init_tf() there.
