### ISSUE TITLE
How to use stylegan2-ada with StyleCLIP

### ISSUE THREAD

**Issue by TheodoreGalanos** [orpatashnik/StyleCLIP#22]
Hello and thanks for sharing your wonderful work!

Was curious, is there a way to utilize ada models with your work?

**Comment by betterze** [comment]
Dear Theodore,

Thank you for your interest in our wok. We just add support to custom StyleGAN2 and StyleGAN2-ada model. You may follow the example [codes](https://github.com/orpatashnik/StyleCLIP#usage-1) to use custom model.

Besides, we prepare the proprecess data for StyleGAN2-ada on afhqcat and afhadog, you could use these two models easily. 

Best Wishes,

Alex

**Comment by TheodoreGalanos** [comment]
Thanks @betterze that's amazing! I will test with my model tomorrow.

**Comment by sam-motamed** [comment]
Hi @betterze , where are the examples codes you mentioned for using StyleCLIP with custom generators?
