### ISSUE TITLE
Latent Mapper Training

### ISSUE THREAD

**Issue by ghunkins** [orpatashnik/StyleCLIP#23]
Incredible work done here - congratulations on the fantastic results.

Is there a timeline for code for training the latent mapper technique by chance? Happy to pitch in on development work as well on that front if necessary.

**Comment by betterze** [comment]
Dear Greg,

Thank you for your interest in our work. I believe we will upload the mapper tonight (06/04/2021) or tomorrow (07/04/2021).

We will inform you once the codes are uploaded.

Best Wishes,

Alex

**Comment by orpatashnik** [comment]
Hi @ghunkins ,
As Alex promised, the mapper's code is available now 😉🎉
If you are interested in joining our development work, please contact us (by mail) 😊
We have a quite long list of things we would like to do
