### ISSUE TITLE
Typos in "Optimization" notebook arguments

### ISSUE THREAD

**Issue by bmachin** [orpatashnik/StyleCLIP#24]
Great work! Thank you for sharing it.

I found the following typos in the "Optimization" notebook:

- in the "Additional arguments" cell, the parameter `size` should be `stylegan_size`. 
- and, in the next cell, instead of `from main import main` it should be `from optimization.run_optimization import main`, I think.

Other than that, it worked perfectly :)

**Comment by orpatashnik** [comment]
Fixed, thanks for noticing!
