### ISSUE TITLE
Colab OOM error when trying to use `latent_path` in the "Optimization" notebook

### ISSUE THREAD

**Issue by bmachin** [orpatashnik/StyleCLIP#25]
As discussed in a previous issue (https://github.com/orpatashnik/StyleCLIP/issues/1), and suggested by @woctezuma I used [this notebook](https://colab.research.google.com/github/omertov/encoder4editing/blob/main/notebooks/inference_playground.ipynb) to project a face image for editing.

I saved the latent with `torch.save(latent, 'latent.pt')` and then uploaded it to the Optmization notebook environment. It loads fine, and the shape seems correct (`torch.Size([18, 512])`, I added some prints in the `run_optimization.py`) but I keep getting the following error:

`RuntimeError: CUDA out of memory. Tried to allocate 1.12 GiB (GPU 0; 15.90 GiB total capacity; 14.74 GiB already allocated; 221.75 MiB free; 14.88 GiB reserved in total by PyTorch)`

which I don't understand, since it should be pretty much the same whether I use a random latent or the one I have saved, or at least that's what I understand by looking at the code. Any ideas?

I'm attaching the latent, just in case: [latent.zip](https://github.com/orpatashnik/StyleCLIP/files/6268970/latent.zip)

Thank you :)

**Comment by orpatashnik** [comment]
Hi @bmachin ,
Thanks for your interest in our project 😊
If I understand correctly, it is the same issue as discussed in [this issue](https://github.com/orpatashnik/StyleCLIP/issues/11).
Let me know if it helps to solve the problem.

**Comment by bmachin** [comment]
Hi @orpatashnik, 

you are correct, and the suggested correction works. 

My bad for the duplicate issue.

Thank you :slightly_smiling_face:
