### ISSUE TITLE
Training on my own dataset?

### ISSUE THREAD

**Issue by tamnguyenvan** [orpatashnik/StyleCLIP#28]
Hello team,
Thank your for this amazing project.
I'd like to train StyleCLIP on own my dataset. I have the images already. What other data do I have to prepare? Could you please let me know the detail steps to train it?

**Comment by betterze** [comment]
Dear Nguyễn,

Thank you for your interest in our work. 

Just to clarify, you want to use our model to manipulate your images (inference), or you want to train another stylegan then use our method to manipulate it?

For inference, please refer to [golbal usage](https://github.com/orpatashnik/StyleCLIP#usage-2). To train another generator, please refer to [stylegan2](https://github.com/NVlabs/stylegan2). 

Best Wishes,

Alex

**Comment by tamnguyenvan** [comment]
Dear @betterze ,
I'd like to train another stylegan (stylegan2-ada) on my own dataset then use your method to manipulate it. So I just have to train stylegan only? No need to train anything else?
Thanks for your quick reply.

**Comment by betterze** [comment]
Dear Nguyễn Văn Tâm,

After you train your stylegan, please do [this](https://github.com/orpatashnik/StyleCLIP#usage-2). There is not a training stage in our method, just a data preprocessing stage. 

Specifically, the following line gets the channel-wise relevance in s space. This is the only stage that takes time (a few hours) in our method.

```
python SingleChannel.py --dataset_name $dataset_name
```

Best Wishes,

Alex

**Comment by 49xxy** [comment]
> 亲爱的@betterze, 我想在我自己的数据集上训练另一个 stylegan (stylegan2-ada) 然后用你的方法来操作它。所以我只需要训练stylegan？不需要训练其他东西吗？ 感谢您的快速回复。

Hi，I want to apply global direction on Stylegan2-ada-PyTorch. Have you tried it before?
