### ISSUE TITLE
Command errored out with exit status 128: git clone -q https://github.com/openai/CLIP.git 

### ISSUE THREAD

**Issue by kennethliukai** [orpatashnik/StyleCLIP#30]
(base) liukai@liukaideMacBook-Pro Downloads % pip install git+https://github.com/openai/CLIP.git
Collecting git+https://github.com/openai/CLIP.git
  Cloning https://github.com/openai/CLIP.git to /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-req-build-jq1hz_wh
ERROR: Command errored out with exit status 128: git clone -q https://github.com/openai/CLIP.git /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-req-build-jq1hz_wh Check the logs for full command output.

Anyone can help, thanks.

**Comment by orpatashnik** [comment]
Hi @kennethliukai ,

Can you give more details please?

**Comment by amao93** [comment]
Maybe the firewall blocks your web access. Try to use another network access point, for example, another wireless network.
