### ISSUE TITLE
What is the meaning of fs3?

### ISSUE THREAD

**Issue by sunpeng1996** [orpatashnik/StyleCLIP#31]
Hi，I am following your work and thank you for your excellent paper.

However, I have some confusion, please help me.

1. What is the meaning of fs3 in the code, I don't know what that means or what it does.
2. What do you estimate with 200 images, which I don't really understand in the paper.
3. How to get delta_i or delta_ic in the paper? 

Looking forward to your responses, thank you very much!!!

**Comment by betterze** [comment]
Dear sunpeng1996,

Thank you for your interest in our work. 

1. fs3 is the delta_ic, it represents how each channel change the output image in CLIP latent space. Please refer to the channelwise relevance subsection in page 6 of [our paper](https://arxiv.org/abs/2103.17249).

2. You mean 100 images in channelwise relevance subsection in page 6?  To get a good estimate delta_ic, which represents the effect of each channel in stylegan s space to CLIP latent space I, we averge the delta_ic we estimate for each image over 100 images. In this way, we get a consistent estimation of delta_ic.

3. You mean the delta_i and delta_ic in equation 6? delta_i is the desired change in image space (estimate by CLIP image encoder space I). During CLIP training, all embeddings are normalized to a unit norm, and therefore only the direction of embedding contains semantic information, while the norm may be ignored. Thus, in well trained areas of the CLIP space, we expect directions on the T and I manifolds that correspond to the same semantic changes to be roughly collinear (i.e., have large cosine similarity), and nearly identical after normalization, such that **delta_i = delta_t**. 

To get delta_i, we just need to get delta_t. And delta_t is the difference between the embedding of two text. For example, when we want to manipulate 'smiling' attribute, we use prompt 'smiling face' and 'face', so **delta_i=delta_t=Unit_Norm(T(smiling face)-T(face))**.

For delta_ic, we first generate an image, manipulate the channel c, so we get two images, one toward the positive direction, one toward negative direction, input these two images into CLIP to get the difference of embedding, 

**delta_ic=unit_norm(I(image_c_p)-I(image_c_n))**. In this way, we get the delta_ic for one image. We repeat this process for 100 images, and average their delta_ic to get a consistent embedding.

Best Wishes,

Alex

**Comment by sunpeng1996** [comment]
Oh！Thank you for your reply. I have understood your thoughts.

I notice that the dimension of fs3 is 6048 x 512, so the 512-d is the embedding dimensions in CLIP, right?
If I understand you correctly, the fs3 represents the mapping relationship between channel changes and CLIP space.

Thank you again for your reply!

**Comment by betterze** [comment]
1. The 512 is the length of embeeding of CLIP space.
2. yep.
