### ISSUE TITLE
how to get dlatent_tmp if I have a real image?

### ISSUE THREAD

**Issue by TomatoBoy90** [orpatashnik/StyleCLIP#33]
thank your great project,I read example in the StyleCLIP_global.ipynb,I find  dlatent_tmp is pregenerated.however,I want to edit a real image ,What shall I do?

**Comment by betterze** [comment]
Thank you for your interest in our work, please refer to [issue 21](https://github.com/orpatashnik/StyleCLIP/issues/21).

**Comment by TomatoBoy90** [comment]
thank you reply so quickly,I got it.
