### ISSUE TITLE
How to edit age

### ISSUE THREAD

**Issue by hushaodong** [orpatashnik/StyleCLIP#34]
How to edit age

**Comment by orpatashnik** [comment]
Hi @hushaodong ,
One possible way to edit age with StyleCLIP is with the global direction method. 
For example, you can give as inputs: neutral = "young face", target = "old face".
There are also other possibilities like "kid face" and "old face"...
For neutral = "young face", target = "old face" I got:
![image](https://user-images.githubusercontent.com/24733041/129266346-4da04909-80d9-4116-8b14-9c34cae9d398.png)
