### ISSUE TITLE
OOM Using 8GB of GPU RAM

### ISSUE THREAD

**Issue by lyn444** [orpatashnik/StyleCLIP#39]
The following command 

python SingleChannel.py --dataset_name $dataset_name
and
python PlayInteractively.py --dataset_name $dataset_name

failed to work on a 2080S with 8GB of GPU Ram.

RuntimeError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 8.00 GiB total capacity; 363.13 MiB already allocated; 768.00 KiB free; 368.00 MiB reserved in total by PyTorch)

Is there anyway to reduce the required GPU RAM?

**Comment by betterze** [comment]
Dear lyn444,

Thank you for your interesting in our work. 

You may reduce [the number of images](https://github.com/orpatashnik/StyleCLIP/blob/main/global_directions/SingleChannel.py#L59). This may decrease the performance a bit. 

Best Wishes,

Alex
