### ISSUE TITLE
[Feature Request] Seeds for randomized initialization of free_generation

### ISSUE THREAD

**Issue by torridgristle** [orpatashnik/StyleCLIP#4]
Simple:
Currently free_generation starts from the average face of the model and diverges from there, but I think it would be far more interesting if it could start with randomized faces when given a seed, like the default generate.py in StyleGAN2-ADA / run_generator.py in StyleGAN2.

Granular Control:
Given that random faces may be a bit _too_ random, perhaps a control for how similar / dissimilar the initial faces should be by lerping with the dlatent_avg like truncation_psi does by default, but applied to the latent of the face itself and not passed to StyleGAN2 so that it can still modify faces with a truncation_psi of 1.0 or whatever else is desired.

Perhaps per layer or per layer range "faux truncation_psi" on the initial latents to allow for wild colors and features but a plain forward-facing head or any other combination of similar / dissimilar elements per layer. If simplified layer ranges are preferred, I'd recommend trying 0-5, 6-11, 12-17 as a starting point. These seem to be where facial shape switches to facial details switches to global coloration.

**Comment by orpatashnik** [comment]
I'm not sure I understood, can you please clarify?

**Comment by torridgristle** [comment]
An option to begin the process with a randomly generated face, as opposed to [this face](https://i.imgur.com/xleN6XD.jpg) each time. So it's like the experiment_type "edit" but instead of a specific user-supplied latent it's just random numbers controlled with a seed.

As for the granular control, adjusting how random the initial face is by lerping it with the [average face](https://i.imgur.com/xleN6XD.jpg) without adjusting the truncation_psi.

As for the further granular control, lerping with the [average face](https://i.imgur.com/xleN6XD.jpg) with control per-layer, like the 4x4 conv0 / conv1, 8x8 conv0 / conv1, 16x16 conv0 / conv1, and so on. The dlatents I've dealt with were just 18 layers of 512 numbers for a 1024px FFHQ-based model, which is what I mean by layer. By lerping the upper layers of this toward the [average face](https://i.imgur.com/xleN6XD.jpg) the range of potential random coloration is limited, but shapes from the lower layers and details in the middle layers won't need to be limited as well.

**Comment by orpatashnik** [comment]
I added seed to the random edited image
