### ISSUE TITLE
wrong result when editing other image with GUI

### ISSUE THREAD

**Issue by juneleung** [orpatashnik/StyleCLIP#42]
Hi, Thanks for your awesome work!
I tried to edit with GUI by `python PlayInteractively.py --dataset_name $dataset_name`. On the official demo image, I get a good result by editing, that's really cool! Unfortunately, when I tried to edit with the other images which I put into the test dataset after e4e inverted (`python GetGUIData.py --dataset_name $dataset_name`), it seems to change to another image after editing? Images are in 1024x1024 resolution as same as the demo given. What should I do editing with other images? Thanks!

official image editing result:
![src](https://user-images.githubusercontent.com/32699460/117537265-60928300-b032-11eb-94fa-a3265c2ffdd8.png)
other image editing result:
![ours](https://user-images.githubusercontent.com/32699460/117537276-6daf7200-b032-11eb-8d0c-777bcea842bb.png)

**Comment by betterze** [comment]
Dear Juneleung,

Thank you for you interest in our work. 

```
# to use custom images, please use e4e encoder to generate latents.pt, and place it in './data/dataset_name/' folder, and add --real flag while running this function.
python GetGUIData.py --dataset_name $dataset_name
```

After place the latents.pt generated by e4e in './data/dataset_name/' folder, run the command with --real flag

```
python GetGUIData.py --dataset_name $dataset_name --real
```

I believe the if you add the --real flag, the problem will solved.

Best Wishes,

Alex

**Comment by juneleung** [comment]
Thanks!
