### ISSUE TITLE
editing latent generated by e4e using interfacegan

### ISSUE THREAD

**Issue by Nivratti** [orpatashnik/StyleCLIP#44]
hello,
Thanks for your great work.

How to get age editing(e4e + interfacegan), quality as shown in paper(page 28-31)?

I tried to save latent vector generated by e4e encoder with the help of code given in  StyleCLIP_global.ipynb.
The code line:
dlatents_loaded=M.W2S(w_plus)

it saving latent in z space. 

I loaded this latent vector in interfacegan to edit, but z space not working properly. The age modification result produced by editing z space not matching with results shown in paper(page no 29).

Is w space necessary to get good result?

**Comment by orpatashnik** [comment]
Hi @Nivratti ,
I recommend you to checkout the colab notebook in the e4e repo (https://github.com/omertov/encoder4editing).
Part of the notebook allows you to edit inverted images with directions obtained by InterFaceGAN.
Good luck!
