### ISSUE TITLE
[Feature Request] Generate Video of Rendered Frames, Included FFMPEG Command

### ISSUE THREAD

**Issue by torridgristle** [orpatashnik/StyleCLIP#5]
I'm sure there's a more elegant way to implement this but my personal solution for rendering a nice video of the frames is to use ffmpeg as installed on Colab and its motion interpolation to generate a smooth video. It may be faster to just save more frames during the process, it may also end up jerkier if it goes back and forth at any point, but I haven't tested these things. I just set it and left it as is on my personal copy.

```!ffmpeg -pattern_type glob -r 5 -i './results/*.png' -filter:v "minterpolate='fps=15:mb_size=8:search_param=8:vsbmc=0:scd=none:mc_mode=obmc:me_mode=bidir'" -vcodec libx264 -crf 28 -pix_fmt yuv420p out.mp4```

It takes the frames as 5fps input and interpolates it 3x to 15fps and saves it in a reasonable quality MP4 with a codec and pixel format that is supported by most devices and websites, as opposed to the output it gives without specifying vcodec and pix_fmt and only tell it to output an mp4. Doing it that way causes issues on Twitter, Tumblr, and some devices just won't play it, so I'd recommend leaving those parts in.

Perhaps the prompt could be the output name like "$description\.mp4" but with some measure taken to truncate long descriptions.

**Comment by orpatashnik** [comment]
I really like the idea!! I will add it (but I will close the issue only when it will be done)

**Comment by orpatashnik** [comment]
Done!
