### ISSUE TITLE
what is the difference between global directions and latent mapper.

### ISSUE THREAD

**Issue by molo32** [orpatashnik/StyleCLIP#50]
what is the difference between global directions and latent mapper.

**Comment by orpatashnik** [comment]
The latent mapper is a network that receives a latent vector w in W+ and returns a delta, such that w + delta corresponds to the image with the desired edit. The mapper has to be trained per text prompts, and the deltas are calculated per latent vector w. Therefore, the latent mapper does not assume that there exists a single direction of the desired edit.

In the global directions approach, we find a single direction in the S space, such that traversing along it changes the desired attributes of the image (according to the text). In this method, we assume that there exists such a global direction exists that works for all the images in StyleGAN's latent space.
