### ISSUE TITLE
[Help] Unbound Local Error

### ISSUE THREAD

**Issue by maparicio23** [orpatashnik/StyleCLIP#52]
How do you fix "UnboundLocalError: local variable 'shape' referenced before assignment". I have no coding experience so hopefully it's not too hard.

**Comment by orpatashnik** [comment]
Hi @maparicio23 ,
Can you please elaborate? Where did you meet this error?
Is it in the alignment of the image?

**Comment by maparicio23** [comment]
I already figured it out. I forget exactly what it was, but I remember it had something to do with the file type.
