### ISSUE TITLE
Head cropping

### ISSUE THREAD

**Issue by qo4on** [orpatashnik/StyleCLIP#56]
Can we make the whole head visible?
![crop](https://user-images.githubusercontent.com/35609308/125113533-39bffe00-e102-11eb-9fa1-fb817da64bfa.jpg)

**Comment by orpatashnik** [comment]
Hi @qo4on ,
The images that can be generated using our method are limited to StyleGAN's capabilities. StyleGAN generates aligned human faces and therefore the head is cropped sometimes.
With that saying, StyleGAN can generate a lot of images with the whole head in the image. 
Can you elaborate on your specific need?

**Comment by qo4on** [comment]
Hi @orpatashnik ,
Yes, ffhq dataset was created with a special align function where they take a line by the 2 points: the center between eyes and the center between lip corners. Then they placed the center on this line:
```
x = eye_to_eye - np.flipud(eye_to_mouth) * [-1, 1]
x /= np.hypot(*x)
x *= max(np.hypot(*eye_to_eye) * 2.0, np.hypot(*eye_to_mouth) * 1.8)
y = np.flipud(x) * [-1, 1]
c = eye_avg + eye_to_mouth * 0.1
quad = np.stack([c - x - y, c - x + y, c + x + y, c + x - y])
qsize = np.hypot(*x) * 2
```
So, we can increase `x` and `y` from this function and get all the cropped areas visible. But I'm not sure that model will understand correctly different input data.

**Comment by orpatashnik** [comment]
Exactly, StyleGAN cannot generate images with different alignment than what it was trained on. Therefore, StyleCLIP can edit only such images.
But Alias Free GAN, which is kind of a new version of StyleGAN, can generate such images! So we have what to expect for 😁
