### ISSUE TITLE
Style space of latent optimization and mapper

### ISSUE THREAD

**Issue by ssumin6** [orpatashnik/StyleCLIP#57]
Hello
I have read your paper and tested some examples on provided Colab. 
It was very interesting, but it left some questions about the style space S and W+.

According to the mentioned paper, it seems that style space S is more disentangled than style space W+. 
Is there any reason why you use w+ space instead of S in the latent optimization and mapper method?

**Comment by orpatashnik** [comment]
Hi @ssumin6 ,
Recently we implemented these two methods in S and found that the results are very similar to those in W+.
I will upload the code this weekend, and also in a newer version of the paper we add these results.

**Comment by orpatashnik** [comment]
The code is available 😊
