### ISSUE TITLE
[Notebook Form] "description" should be specified as a String

### ISSUE THREAD

**Issue by torridgristle** [orpatashnik/StyleCLIP#6]
Currently the form with the description input is `description = 'A person with purple hair' #@param` but this results in the user having to add quotes to the description themselves. Instead, it should be `description = 'A person with purple hair' #@param {type:"string"}` to have Google Colab apply the quotes automatically on its own.

I think `latent_path = None #@param` should also have `{type:"string"}` specified in case of spaces, and to avoid needing the user to add quotes on their own.

**Comment by orpatashnik** [comment]
Thanks, will be fixed :)
I really appreciate all your suggestions!

**Comment by orpatashnik** [comment]
Fixed
