### ISSUE TITLE
Speeding up trainer - avenue for exploring

### ISSUE THREAD

**Issue by johndpope** [orpatashnik/StyleCLIP#60]
I watched some youtube videos and came across pytorch lightning which supposedly simplifies distributed trainining.
https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html
(I don't want to wait 10 hours for training to finish / mainly because of the power usage on my gpu)

**Comment by orpatashnik** [comment]
Hi @johndpope ,

I think that 10 hours to train a network is relatively fast 😊
I did not plan to support multi-gpus, and I think there are easier ways than integrating into the pytorch lighting framework.
If you implement that, I invite you to open a pull request 🙂

Or

**Comment by orpatashnik** [comment]
Hi @johndpope ,

I know StyleGAN-NADA pretty well 😉
There is a conceptual difference between StyleCLIP and NADA: 
StyleCLIP can edit the image within the domain of the generator. For example, in the case of the generator that was trained on FFHQ, the result images can be realistic faces only. StyleCLIP edits images by traversing in the latent space.
NADA on the other hand, changes the weights of the generator, and can therefore go out-of-domain. As we show in the paper, after having the new generator, we can further use latent space traversal methods (e.g., StyleCLIP) to do such editing.

Regarding the training time and the need for exploration. Note that in StyleCLIP we introduce three different methods, each with its pros and cons. For exploration, I think that the global directions and the optimization should be better than the mapper. 

For the type of editing that you tried [here](https://github.com/nerdyrodent/VQGAN-CLIP/issues/13), NADA indeed fits better. Let me know if you want to consult more about the differences between the methods 😀

BTW, if you choose to finish the training of the mapper it would be very interesting for me to know how much time did it take. I didn't have such a smoke hot GPU 😉

Or
