### ISSUE TITLE
How to get the example_celebs.pt?

### ISSUE THREAD

**Issue by jiyidefeng1990** [orpatashnik/StyleCLIP#62]
I want to use the function "Editing via Latent Mapper", but how to get the input "example_celebs.pt" from another picture?

**Comment by orpatashnik** [comment]
To edit a real image, it is required to invert the image. This can be done with methods such as [pSp](https://github.com/eladrich/pixel2style2pixel), [e4e](https://github.com/omertov/encoder4editing), [Restyle](https://github.com/yuval-alaluf/restyle-encoder).
For more information, please see this issue: [](https://github.com/orpatashnik/StyleCLIP/issues/1).
You can also check the 'global directions' colab notebook, in which the inversion using e4e is already integrated.
