### ISSUE TITLE
How to improve e4e inversion

### ISSUE THREAD

**Issue by smithee77** [orpatashnik/StyleCLIP#64]
Hi, first of all thanks your your amazing work :)

Is there a way to improve e4e image inversion (e.g. increasing some kind of iteration parameters?). I've tried with some faces and sometimes the inverted result has little resemblance with original one...
many thanks in advance

**Comment by orpatashnik** [comment]
Hi @smithee77 ,

I am happy to hear that you liked our work 😊.
Image inversion is a quite active research area and in the past year, there are quite a lot of works on this subject.
I recommend you to take a look on [ReStyle](https://github.com/yuval-alaluf/restyle-encoder), which is a newer work with more accurate results.

Or

**Comment by smithee77** [comment]
thank you very much! definitely I'll take a look and try to figure out how to use ReStyle with your CLIP notebook :)
