### ISSUE TITLE
How to edit character in global direction

### ISSUE THREAD

**Issue by ZziTaiLeo** [orpatashnik/StyleCLIP#74]
I don’t know how to edit, I edit Trump but it doesn’t change. I use other peson's photo  and  set the neutral is "person", target is "Donald Trump" .  What should I do if I want edit the photo to celebrity

**Comment by orpatashnik** [comment]
Hi @ZziTaiLeo ,

To edit an image toward a character we reccommd using the optimization or the mapper.
The global direction method is usually not good enough for that.

**Comment by ZziTaiLeo** [comment]
> Hi @ZziTaiLeo ,
> 
> To edit an image toward a character we reccommd using the optimization or the mapper. The global direction method is usually not good enough for that.

thank you very much!
