### ISSUE TITLE
alpha and beta modification in mapper playground

### ISSUE THREAD

**Issue by rotem154154** [orpatashnik/StyleCLIP#81]
is there any way to add alpha and beta modification found in StyleCLIP_global notebook to mapper_playground?
and if not is there any way to control the amount of the effect of the mapping? 
great work Or, Zongze and any one who collaborate!
כל הכבוד

**Comment by orpatashnik** [comment]
Hi @rotem154154 ,
For a given latent code, the mapper outputs an offset for obtaining the target edit.
You can control the edit strength by traversing on the direction of the offset, with different magnitude. This is not implemented in the code, but it is quite easy to implement it.
A disentanglement parameter cannot be used with the mapper.

Hope this helps and thanks for the compliment,
Or
